shellCheck

diff --git a/dgx/rubmit b/dgx/rubmit
--- a/dgx/rubmit
+++ b/dgx/rubmit
@@ -20,39 +20,39 @@ follow=True
 #####################################################################################
 print_usage()
 {
-    echo 'Script to submit a runai job.'
+    echo "Script to submit a runai job."
     echo
-    echo 'Brief syntax:'
+    echo "Brief syntax:"
     echo "${0##*/} [OPTIONS(0)...] [ : [OPTIONS(N)...]] [-- <cmd>]"
     echo
-    echo 'Full syntax:'
+    echo "Full syntax:"
     echo "${0##*/} [-h|--help] [-f|--follow <val>] [-d|--dir <val>]"
-    echo '                  [-g|--gpu <val>] [-n|--node <val>]'
-    echo '                  [-j|--job-name <val>] [-i|--im-name <val>]'
-    echo '                  [-e|--env <val>] [-o|--overwrite <val>]'
-    echo '                  [-c|--check <val>] [-- <cmd>]'
+    echo "                  [-g|--gpu <val>] [-n|--node <val>]"
+    echo "                  [-j|--job-name <val>] [-i|--im-name <val>]"
+    echo "                  [-e|--env <val>] [-o|--overwrite <val>]"
+    echo "                  [-c|--check <val>] [-- <cmd>]"
     echo
-    echo 'options without args:'
-    echo '-h, --help                : Print this help.'
+    echo "options without args:"
+    echo "-h, --help                : Print this help."
     echo
-    echo 'options with args:'
-    echo '-d, --dir <val>           : Directory to run from. Default: `pwd`.'
+    echo "options with args:"
+    echo "-d, --dir <val>           : Directory to run from. Default: \`pwd\`."
     echo "-g, --gpu <val>           : Number of gpus to submit. Default: ${gpu}."
-    echo '-n, --node <val>          : Node to run on. Default is any.'
-    echo '-j, --job-name <val>      : Name of submitted job. If not given, name'
-    echo '                             will be taken from the command (with `python `'
-    echo '                             removed). If default command has been used, name'
-    echo '                             is taken from environment variable RUNAI_NAME.'
-    echo '                             If RUNAI_NAME missing, error.'
-    echo '-i, --im-name <val>       : Name of docker image to be run. Default from'
-    echo '                             environment variable `RUNAI_IM`.'
-    echo '-e, --env <val>           : Comma-separated list of variables to copy'
-    echo '                             from dgx to job. Default from'
-    echo '                             environment variable `RUNAI_ENVS`.'
+    echo "-n, --node <val>          : Node to run on. Default is any."
+    echo "-j, --job-name <val>      : Name of submitted job. If not given, name"
+    echo "                             will be taken from the command (with \`python \`"
+    echo "                             removed). If default command has been used, name"
+    echo "                             is taken from environment variable \`RUNAI_NAME\`."
+    echo "                             If RUNAI_NAME missing, error."
+    echo "-i, --im-name <val>       : Name of docker image to be run. Default from"
+    echo "                             environment variable \`RUNAI_IM\`."
+    echo "-e, --env <val>           : Comma-separated list of variables to copy"
+    echo "                             from dgx to job. Default from"
+    echo "                             environment variable \`RUNAI_ENVS\`."
     echo "-f, --follow <val>        : After submitting, follow job. Default: ${follow}."
-    echo '-o, --overwrite <val>     : If job with same name exists, should it be'
+    echo "-o, --overwrite <val>     : If job with same name exists, should it be"
     echo "                             deleted? Default: ${overwrite}."
-    echo '-c, --check <val>        : If true, and cmd is given, get filename and check it exists.'
+    echo "-c, --check <val>        : If true, and cmd is given, get filename and check it exists."
     echo "                             deleted? Default: ${check}."
     echo
     echo "NB: if \`-- <cmd>\` not given, \`${default_cmd}\` is used."
@@ -123,15 +123,15 @@ done
 # Post-process input arguments
 #####################################################################################
 # default command
-: ${cmd:=$default_cmd}
+: "${cmd:=$default_cmd}"
 
 # if job name not given, figure one out
 if [ "${job_name}" == "" ]; then
     if [ "${cmd}" != "${default_cmd}" ]; then
         job_name="${cmd}"
         # remove "python " and ".py"
-        job_name="$(echo $job_name | sed -E -e 's/.*python//')"
-        job_name="$(echo $job_name | sed -E -e 's/\.py//')"
+        job_name="$(echo "$job_name" | sed -E -e 's/.*python//')"
+        job_name="$(echo "$job_name" | sed -E -e 's/\.py//')"
         # remove dashes, and replace underscores and spaces with dashes
         job_name="${job_name//-/}"
         job_name="${job_name// /-}"
@@ -141,7 +141,7 @@ if [ "${job_name}" == "" ]; then
         job_name="${default_job_name}"
     # if default command used and env var not set, error.
     else
-        echo 'Job name not given, default command used. Please set `RUNAI_NAME` for default job name.'
+        echo "Job name not given, default command used. Please set \`RUNAI_NAME\` for default job name."
         exit 1
     fi
     # max job name length
@@ -150,9 +150,9 @@ fi
 
 if [ "${env_vars}" != "" ]; then
     # remove spaces from env list
-    env_vars="${env_vars//[[:blank:]]/}"
+    env_vars_str="${env_vars//[[:blank:]]/}"
     # split at commas and convert to array
-    env_vars=($(echo $env_vars | tr "," "\n"))
+    env_vars=($(echo $env_vars_str | tr "," "\n"))
     env_cmd=""
     for i in "${env_vars[@]}"; do
         env_cmd="${env_cmd} -e $i=${!i}"
@@ -165,7 +165,7 @@ echo "Num GPUs: ${gpu}"
 echo "Requested node: ${node:-Any}"
 echo "Job name: ${job_name}"
 echo "Image name: ${im_name}"
-echo "Env vars: ${env_vars}"
+echo "Env vars: ${env_vars_str}"
 echo "Overwrite?: ${overwrite}"
 echo "Check?: ${check}"
 echo
@@ -202,20 +202,20 @@ cd "$script_dir"
 
 if [ "$overwrite" == True ]; then
     # Delete previously running job if one by same name exists
-    runai delete job $job_name > /dev/null 2>&1 || true
+    runai delete job "$job_name" > /dev/null 2>&1 || true
 fi
 
 #####################################################################################
 # Submit job
 #####################################################################################
 runai submit --name "$job_name" \
-    $node $port \
-    -i $im_name \
-    -g $gpu \
+    "$node" \
+    -i "$im_name" \
+    -g "$gpu" \
     --host-ipc \
-    -v ${HOME}:${HOME} \
+    -v "${HOME}":"${HOME}" \
     --backoff-limit 0 \
-    -- ${script_dir}/runai_startup.sh ${env_cmd} -d ${run_dir} -- ${cmd}
+    -- "${script_dir}"/runai_startup.sh ${env_cmd} -d "${run_dir}" -- ${cmd}
 
 #####################################################################################
 # If desired, job status until RUNNING
@@ -225,7 +225,7 @@ if [ "${follow}" == True ]; then
     # Get job status
     function get_status {
         pat="status: ([a-zA-Z]*)"
-        [[ $(runai describe job $job_name -o yaml) =~ $pat ]] 2> /dev/null
+        [[ $(runai describe job "$job_name" -o yaml) =~ $pat ]] 2> /dev/null
         echo "${BASH_REMATCH[1]}"
     }
 
@@ -234,14 +234,14 @@ if [ "${follow}" == True ]; then
     while true; do
         new_status=$(get_status)
         if [[ "$new_status" != "" && "$new_status" != "$old_status" ]]; then
-            echo Job status: $new_status
+            echo Job status: "$new_status"
             old_status="$new_status"
         fi
         if [[ "$new_status" == "Failed" || "$new_status" == "Succeeded" || "$new_status" == "Completed" ]]; then
-            runai logs $job_name
+            runai logs "$job_name"
             break
         elif [[ "$new_status" == "Running" ]]; then
-            runai logs ${job_name} -f
+            runai logs "${job_name}" -f
         fi
         sleep .5
     done
